### ISSUE TITLE
Package RAR classes in a JAR

### ISSUE THREAD

**Issue by gastaldi** [vert-x3/vertx-jca#7]
I'm working on the WildFly Swarm Vert.x Fraction. In order to make this RAR deployable, it's highly recommended to declare it as a module (using the jboss-modules mechanism). 
I have declared vert.x as a WildFly module (see https://github.com/gastaldi/wildfly-swarm-vertx/blob/master/modules/src/main/resources/modules/io/vertx/main/module.xml)

However in order to achieve that, I need the vertx-jca-adapter.jar (generated from the rar/ project) but I couldn't find it in any maven repository

**Comment by cescoffier** [comment]
Fixed in the master branch.

**Comment by cescoffier** [comment]
Here it is: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-jca-adapter/3.3.0-SNAPSHOT/vertx-jca-adapter-3.3.0-20160607.190603-332.jar
